> ✏️프로미스

###### 자바스크립트는 비동기 처리를 위한 하나의 패턴으로 "콜백 함수"를 사용한다
###### 하지만 전통적인 콜백 패턴은 "콜백 헬"로 인해 가독성이 나쁘고, 에러 처리가 곤란하며 비동기를 한 번에 처리하는 데에도 한계가 있다
###### ES6에서는 비동기 처리를 위한 또 다른 패턴으로 Promise(프로미스)를 도입했다.
###### 프로미스의 장점은 전통적인 콜백 패턴이 가진 단점 보완 및 비동기 처리 시점을 명확하게 표현할 수 있다는 것!

</br>
</br>

# 비동기 처리를 위한 콜백 패턴의 단점

### 1, 콜백 헬

콜백 함수를 통해 비동기 처리 결과에 대한 후속 처리를 수행하는 비동기 함수가 비동기 처리결과를 가지고 </br>
또 다시 비동기 함수를 호출하게 되면, **콜백함수 호출이 중첩되어 복잡도가 높아지는 현상인 "콜백 헬"이 나타나게 된다**

##### 📍콜백 헬의 전형적인 사례
![image](https://github.com/mobi-community/mobi-2th-book-study/assets/134191815/fcafa392-8135-45af-a98c-74cd2b591185)


비동기 함수 호출 시 함수 내부의 비동기로 동작하는 코드가 완료되지 않았다고 해도 기다리지 않고 즉시 종료됨</br>
즉, 비동기 함수 내부의 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료된다

###### 비동기 함수: 함수 내부에 비동기로 동작하는 코드를 포함한 함수


비동기 함수 내부의 비동기로 동작하는 코드에서 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않음

```jsx
let g = 0;

//비동기 함수인 setTimeout 함수는 콜백 함수의 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하지 못한다
setTimeout(() => { g = 100; }, 0);
console.log(g); //0
```

따라서 비동기 함수의 처리 결과(서버의 응답 등)에 대한 후속 처리는 비동기 함수 내부에서 수행해야 한다</br>
보통, 비동기 함수를 범용적으로 사용하기 위해 비동기 함수에 비동기 처리 결과에 대한 후속처리를 수행하는 "콜백 함수"를 전달함



### 2, 에러 처리의 한계

#### 에러는 호출자 방향으로 전파된다


_setTimeout_ 콜백함수가 실행될 때 _setTimeout_ 함수는 이미 콜 스택에서 제거된 상태이다

즉, _setTimeout_ 함수의 콜백함수를 호출한 것은 _setTimeout_ 이 아니기 때문에,</br>
_setTimeout_ 콜백함수가 발생시킨 에러는 _catch_ 블록에서 캐치되지 않는다.


```jsx
try {
  setTimeout(() => { throw new Error('Error!'); }, 1000);
} catch (e) {
  //에러를 캐치하지 못한다
  console.error('캐치한 에러', e);
}
```

지금까지 살펴본 비동기 처리를 위한 콜백 패턴은 콜백 헬이나 에러 처리가 곤란하다는 문제 </br>
➲ 극복하기 위해 "프로미스" 도입


# 프로미스의 생성

promise 생성자 함수를 `new` 연산자와 함께 호출하면 프로미스 객체를 생성한다

###### reject와 resolve를 인수로 전달받는다

```jsx
//프로미스 생성
const prromise = new Promise((resolve, reject) => {
  //Promise 함수의 콜백 함수 내부에서 비동기 처리 수행
  if (/*비동기처리 성공*/) {
    resolve('result');
  } else { /*비동기처리 실패*/
    reject('failure reason');
  }
});
```
get을 프로미스를 사용해 다시 구현

```jsx
// GET 요청을 위한 비동기 함수
const promiseGet = (url) => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open("GET", url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) {
          // 성공적으로 응답 받을시 resolve 호출
          resolve(JSON.parse(xhr.response));
      }
      else {
        //에러 처리를 위해 reject함수 호출
        reject(new Error(xhr.status));
      }
    };
  });
};

// promiseGet 함수는 프로미스를 반환
promiseGet("https://jsonplaceholder.typicode.com/posts/1");
```


프로미스는 다음과 같이 현재 비동기 처리가 어떻게 진행되고 있는지를 나타내는 '상태' 정보를 갖음

![image](https://github.com/mobi-community/mobi-2th-book-study/assets/134191815/d5be9060-646d-4257-97bb-7d082f92a485)


생성된 직후 프로미스는 기본적으로 _pending_ 상태, 이후 처리 결과에 따라 다음과 같이 상태 변경된다

- 비동기 처리 성공: `resolve` 함수를 호출해 프로미스를 `fulfiled` 상태로 변경
- 비동기 처리 실패: `reject` 함수를 호출해 프로미스를 `rejected` 상태로 변경
- fulfilled 또는 rejected 상태를 `settled`상태라고 한다(pending 이 아닌 상태로 비동기 처리가 수행된 상태를 말함) 

###### settled 상태가 되면 더는 다른 상태로 변화할 수 없다

#### 이처럼 프로미스의 상태는 resolve 또는 reject 함수를 호출하는 것으로 결정됨

```jsx
//fulfilled된 프로미스
const fulfilled = new Promise(resolve =>> resolve(1));
```

##### 개발자 도구

![image](https://github.com/mobi-community/mobi-2th-book-study/assets/134191815/8d78d9b2-9de7-4ee6-9748-3d0b68305792)

비동기 처리 성공시 프로미스는 _pending_ 상태에서 _fulfilled_ 상태로 변화 </br>
비동기 처리 결과인 1을 값으로 갖음


```jsx
//rejcted된 프로미스
const rejected = new Promisse((_, reject) => reject(new Error('error occured'));
```

##### 개발자 도구
![image](https://github.com/mobi-community/mobi-2th-book-study/assets/134191815/ee6bbca6-273f-4029-bf0b-26c8aed06a2d)


비동기 처리 실패시 프로미스는 _pending_ 상태에서 _rejected_ 상태로 변화 </br>
비동기 처리 결과인 Error 객체를 값으로 갖음

#### 프로미스는 비동기 처리 상태와 처리 결과를 관리하는 객체


# 프로미스의 후속 처리 메서드
_then, catch, finally_

#### 프로미스의 비동기 처리 상태가 변화하면 후속처리 메서드에 인수로 전달한 콜백 함수가 선택적으로 호출됨

모든 후속처리 메서드는 프로미스를 반환하며, 비동기로 동작

</br>
</br>

##### Promise.prototype.then

`then`: 두 개의 콜백 함수를 인수로 전달받는다

- 프로미스가 fulfilled 상태가 되면 호출, 프로미스의 비동기 처리 결과를 인수로 전달받음
- 프로미스가 rejected 상태가 되면 호출, 에러를 인수로 전달받음

```jsx
// fulfilled: 성공 처리 콜백 함수
new Promise((resolve) => resolve("fulfilled"))
  .then((v) => console.log(v), (e) => console.error(e));

// rejected: 실패 처리 콜백 함수
new Promise((_, reject) => reject(new Error("rejected")))
  .then((v) => console.log(v), (e) => console.error(e));
```


##### Promise.prototype.catch

`catch`: 한 개의 콜백함수를 인수로 전달받는다

catch메서드의 콜백함수는 프로미스가 _rejected_ 상태인 경우만 호출됨

```jsx
// rejected: 실패 처리 콜백 함수
new Promise((_, reject) => reject(new Error("rejected"))).catch((e) =>
  console.error(e) //Error: rejected
);
```


##### Promise.prototype.finally

`finally`: 한개의 콜백함수를 인수로 전달받는다

프로미스의 성공 또는 실패와 상관없이 무조건 한 번은 호출됨

```jsx
//finally: 프로미스의 상태와 상관없이 공통적으로 수행해야 할 처리 내용이 있을 때 사용
new Promise(() => {})
  .finally(() => console.log("finally"));




